name: Deployment Workflow to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  # run_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '7.4'

  #     - name: Install dependencies
  #       run: composer install

  #     - name: Run tests
  #       run: vendor/bin/phpunit

  build_and_push:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/byecar-web-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /byecar-web-server
            docker-compose down
            git pull origin main
            docker-compose build
            docker-compose up -d
            docker exec -it php /bin/bash -c "chmod -R 777 storage"
            docker exec -it php /bin/bash -c "cp .env.example .env"
            docker exec -it php /bin/bash -c "composer install"
            docker exec -it php /bin/bash -c "php artisan key:generate"
            docker exec -it php /bin/bash -c "php artisan migrate"


            

